### PR TITLE
Add Gradle/Maven builds

### PR DESCRIPTION
**Pull request by SoftlySplinter**
## Summary of Changes
* Added a Gradle build to the project.
* Added a Maven build to the project.
* Some small restructures to make the Gradle/Maven builds more intuiative.
* Added GitHub Actions for CI builds.

### CODE REVIEW

**Comment by PhilWakelin** [comment]
Can we simplify the exception handling [logic ](https://github.com/cicsdev/cics-java-liberty-link/commit/0a86095f261535ef6eb78cf90b4a7e430d8ce5f6#diff-3b22358535917be3b8af937e062ef5d3be74eb548b60b8d7702fa1f34875a434) to be JCICS version agnostic

```
} catch (InvalidRequestException | ContainerErrorException | ChannelErrorException | CCSIDErrorException
				| CodePageErrorException e) {
//              If compiling against CICS 5.6 or higher: add "LengthErrorException" as shown in the following commented out lines
//		} catch (InvalidRequestException | ContainerErrorException | ChannelErrorException | CCSIDErrorException
//				| CodePageErrorException | LengthErrorException e) {
```

to

```
} catch (CicsConditionException  e) {

```

**Comment by PhilWakelin** [comment]
The CJLL transaction should be renamed to not use a C prefix as otherwise CICS will warn that its reserved for CICS usage. I suggest `WLPH`

**Comment by PhilWakelin** [comment]
Can we update `@CICSProgram("HELLOWLP") ` in HelloLiberty.java from using a string literal to a defined static.

**Comment by PhilWakelin** [comment]
The link in the [readme](https://github.com/SoftlySplinter/cics-java-liberty-link/blob/main/README.md) to this [topic](https://developer.ibm.com/cics/2016/11/14/link-to-liberty-now-available-in-cics-ts-v5-3/) is no longer valid 
I suggest just link to the IBM Docs topic https://www.ibm.com/docs/en/cics-ts/6.1?topic=djariljs-linking-java-applications-in-liberty-jvm-server-by-using-cicsprogram-annotation

**Comment by PhilWakelin** [comment]
Can we update the README to refer to running the sample via the supplied transaction WLPH/CJLL

**Comment by PhilWakelin** [comment]
In the transaction [bundlepart ](https://github.com/SoftlySplinter/cics-java-liberty-link/blob/main/cics-java-liberty-link-bundle/src/main/bundleParts/CJLL.transaction), this comment doesn't make sense, what's the `CICSUserGreeter `
> Note: the HELLOWLP program is automatically defined with the CICSUserGreeter is installed
into a Liberty JVM server.

**Review by IvanHargreaves — APPROVED** [review]

**Pull request merged**
